export const products = [
    // Fruits
    {
        id: 1,
        name: "Organic Bananas",
        category: "Fruits",
        price: 150,
        originalPrice: 200,
        rating: 4.8,
        reviews: 234,
        image: "🍌",
        badge: "Sale",
        availableQuantity: 50,
    },
    {
        id: 2,
        name: "Fresh Avocados",
        category: "Fruits",
        price: 300,
        rating: 4.9,
        reviews: 189,
        image: "🥑",
        badge: "Popular",
        availableQuantity: 30,
    },
    {
        id: 7,
        name: "Red Apples (6pc)",
        category: "Fruits",
        price: 600,
        rating: 4.7,
        reviews: 178,
        image: "🍎",
        badge: "New",
        availableQuantity: 45,
    },
    {
        id: 9,
        name: "Fresh Oranges (1kg)",
        category: "Fruits",
        price: 550,
        rating: 4.6,
        reviews: 145,
        image: "🍊",
        availableQuantity: 60,
    },
    {
        id: 10,
        name: "Pineapple",
        category: "Fruits",
        price: 350,
        rating: 4.8,
        reviews: 90,
        image: "🍍",
        availableQuantity: 25,
    },

    // Vegetables
    {
        id: 11,
        name: "Organic Spinach",
        category: "Vegetables",
        price: 120,
        rating: 4.7,
        reviews: 112,
        image: "🥬",
        availableQuantity: 40,
    },
    {
        id: 12,
        name: "Red Tomatoes (1kg)",
        category: "Vegetables",
        price: 250,
        originalPrice: 320,
        rating: 4.5,
        reviews: 201,
        image: "🍅",
        badge: "Sale",
        availableQuantity: 70,
    },
    {
        id: 13,
        name: "Bell Peppers (3pk)",
        category: "Vegetables",
        price: 400,
        rating: 4.8,
        reviews: 87,
        image: "🫑",
        availableQuantity: 35,
    },
    {
        id: 14,
        name: "Fresh Carrots (1kg)",
        category: "Vegetables",
        price: 180,
        rating: 4.6,
        reviews: 156,
        image: "🥕",
        availableQuantity: 55,
    },
    {
        id: 15,
        name: "Broccoli",
        category: "Vegetables",
        price: 300,
        rating: 4.7,
        reviews: 134,
        image: "🥦",
        availableQuantity: 28,
    },

    // Dairy
    {
        id: 3,
        name: "Farm Eggs (12pc)",
        category: "Dairy",
        price: 550,
        rating: 4.7,
        reviews: 312,
        image: "🥚",
        availableQuantity: 100,
    },
    {
        id: 4,
        name: "Organic Milk",
        category: "Dairy",
        price: 280,
        rating: 4.6,
        reviews: 156,
        image: "🥛",
        availableQuantity: 40,
    },
    {
        id: 8,
        name: "Greek Yogurt",
        category: "Dairy",
        price: 450,
        rating: 4.8,
        reviews: 203,
        image: "🥄",
        availableQuantity: 32,
    },
    {
        id: 16,
        name: "Cheddar Cheese",
        category: "Dairy",
        price: 850,
        rating: 4.8,
        reviews: 167,
        image: "🧀",
        badge: "Popular",
        availableQuantity: 20,
    },

    // Meat
    {
        id: 17,
        name: "Chicken Breast (1kg)",
        category: "Meat",
        price: 1200,
        rating: 4.8,
        reviews: 245,
        image: "🍗",
        availableQuantity: 25,
    },
    {
        id: 18,
        name: "Premium Steak",
        category: "Meat",
        price: 2500,
        originalPrice: 3000,
        rating: 4.9,
        reviews: 189,
        image: "🥩",
        badge: "Sale",
        availableQuantity: 15,
    },
    {
        id: 19,
        name: "Ground Beef (500g)",
        category: "Meat",
        price: 950,
        rating: 4.7,
        reviews: 143,
        image: "🍖",
        availableQuantity: 30,
    },

    // Bakery
    {
        id: 6,
        name: "Whole Wheat Bread",
        category: "Bakery",
        price: 250,
        rating: 4.5,
        reviews: 245,
        image: "🍞",
        availableQuantity: 40,
    },
    {
        id: 20,
        name: "Fresh Croissants (4pk)",
        category: "Bakery",
        price: 450,
        rating: 4.8,
        reviews: 167,
        image: "🥐",
        badge: "New",
        availableQuantity: 24,
    },
    {
        id: 21,
        name: "Bagels (6pk)",
        category: "Bakery",
        price: 400,
        rating: 4.6,
        reviews: 123,
        image: "🥯",
        availableQuantity: 36,
    },

    // Seafood
    {
        id: 5,
        name: "Fresh Salmon",
        category: "Seafood",
        price: 1800,
        originalPrice: 2200,
        rating: 4.9,
        reviews: 98,
        image: "🐟",
        badge: "Sale",
        availableQuantity: 18,
    },
    {
        id: 22,
        name: "Large Shrimp (Frozen)",
        category: "Seafood",
        price: 1500,
        rating: 4.7,
        reviews: 112,
        image: "🦐",
        availableQuantity: 22,
    },

    // Beverages
    {
        id: 23,
        name: "Orange Juice (1L)",
        category: "Beverages",
        price: 450,
        rating: 4.6,
        reviews: 256,
        image: "🧃",
        availableQuantity: 45,
    },
    {
        id: 24,
        name: "Coffee Beans (500g)",
        category: "Beverages",
        price: 1200,
        rating: 4.8,
        reviews: 234,
        image: "☕",
        badge: "Popular",
        availableQuantity: 30,
    },
    {
        id: 25,
        name: "Green Tea Box",
        category: "Beverages",
        price: 350,
        rating: 4.7,
        reviews: 98,
        image: "🍵",
        availableQuantity: 50,
    },

    // Snacks
    {
        id: 26,
        name: "Salted Almonds",
        category: "Snacks",
        price: 850,
        rating: 4.8,
        reviews: 167,
        image: "🥜",
        availableQuantity: 40,
    },
    {
        id: 27,
        name: "Potato Chips",
        category: "Snacks",
        price: 200,
        rating: 4.5,
        reviews: 245,
        image: "🥔",
        availableQuantity: 80,
    },
    {
        id: 28,
        name: "Dark Chocolate",
        category: "Snacks",
        price: 450,
        rating: 4.9,
        reviews: 312,
        image: "🍫",
        badge: "Popular",
        availableQuantity: 35,
    },
];
